version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-events-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: events_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  java-app:
    container_name: java-app
    build: .
    restart: on-failure
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql-events-db
      DB_PORT: 3306
      DB_NAME: events_db
      DB_USER: user
      DB_PASSWORD: password

volumes:
  mysql-data: